name: Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:
    name: CI
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        # Run on the latest minor release of Go 1.20:
        go-version: ^1.20
      id: go


    - name: Ensure all files were formatted as per gofmt
      run: |
        [ "$(gofmt -l $(find . -name '*.go') 2>&1)" = "" ]

    - name: Run tests
      run: |
        go test -c github.com/google/nftables
        sudo nft --version
        sudo nft flush ruleset
        sudo nft add table inet filter
        sudo nft add ct expectation inet filter expect '{ protocol tcp ; dport 53 ; timeout 2s ; size 1 ; }'
        sudo NLDEBUG=1 ./nftables.test -test.v -run_system_tests -test.run=TestCtExpect
